version: '{build}'

branches:
    only: 
    - master
    
    
environment:
    matrix:
    - name: win32
      platform: x86
      toolchain: msvc2015
      qt: 5.11.3
      toolchaintype: ms
      
    - name: win64
      platform: amd64
      toolchain: msvc2015_64
      qt: 5.11.3
      toolchaintype: ms
    
    - name: mingw32
      platform: mingw
      toolchain: mingw53_32
      qt: 5.11.3
      toolchaintype: mw
      
before_build:
    - set QTDIR=C:\Qt\%qt%\%toolchain%
    - echo "qtdir=%QTDIR%"
    - set PATH=%PATH%;%QTDIR%\bin
    - echo "platform=%platform%"
    - if "%platform%"=="x86"  call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
    - if "%platform%"=="amd64" call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
    - if "%platform%"=="amd64" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
    - if "%platform%"=="mingw" PATH=%PATH%;C:\Qt\Tools\mingw530_32
    - echo "path=%PATH%"
    
build_script:
    - qmake Complier.pro
    - if "%toolchaintype%"=="ms" nmake
    - if "%toolchaintype%"=="mw" mingw32-make

after_build:
  - if "%APPVEYOR_DEPLOY%"=="true" windeployqt bin\complier_tiny_c.exe --qmldir %QTDIR%\qml
  
artifacts:
  - path: bin
    
deploy:
    provider: GitHub
    auth_token: 183bb4d650be1da439cea601566a7131e98cc4d5
    description: 'Appveyor Triggered Build'
    draft: false
    prerelease: false
    on:
        APPVEYOR_DEPLOY: true
