version: '{build}'

branches:
    only: 
    - master
    
environment:
    matrix:
    - name: win32
      platform: x86
      buildtc: msvc2017
      qt: 5.12
      suffix: msvc2017
      
    - name: win64
      platform: amd64
      buildtc: msvc2017_64
      qt: 5.12
      suffix: msvc2017
    
    - name: mingw32
      platform: mingw
      buildtc: mingw73_32
      qt: 5.12
      suffix: mingw
      
before_build:
    - set vs="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build"
    - set PATH=%PATH%;C:\Qt\%qt%\%buildtc%\bin"
    - set QTDIR=C:\Qt\%qt%\%buildtc%
    - if "%platform%"== "amd64" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    - if "%platform%"== "x86" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"

build_script:
    - qmake
    - nmake

after_build:
  - if "%APPVEYOR_DEPLOY%"=="true" windeployqt bin\complier_tiny_c.exe --qmldir %QTDIR%\qml
  
artifacts:
  - path: bin
    
deploy:
    provider: GitHub
    auth_token: 183bb4d650be1da439cea601566a7131e98cc4d5
    description: 'Appveyor Triggered Build'
    draft: false
    prerelease: false
    on:
        APPVEYOR_DEPLOY: true
