version: '{build}'

branches:
    only: 
    - master
    
environment:
    matrix:
    - name: win32
      platform: x86
      toolchain: msvc2017
      qt: 5.12
      
    - name: win64
      platform: amd64
      toolchain: msvc2017_64
      qt: 5.12
    
    - name: mingw32
      platform: mingw
      toolchain: mingw73_32
      qt: 5.12
      
before_build:
    - set vs="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build"
    - set QTDIR=C:\Qt\%qt%\%toolchain%
    - set PATH=%PATH%;%QTDIR%\bin
    - if "%platform%"== "amd64" call "%vs%\vcvars64.bat"
    - if "%platform%"== "x86" call "%vs%\vcvars32.bat"
    - echo "enviroment_vs=%vs%"
    - echo "qtdir=%QTDIR%"
    - echo "path=%PATH%"
    - echo "platform=%platform%"
    
build_script:
    - qmake Complier.pro
    - nmake

after_build:
  - if "%APPVEYOR_DEPLOY%"=="true" windeployqt bin\complier_tiny_c.exe --qmldir %QTDIR%\qml
  
artifacts:
  - path: bin
    
deploy:
    provider: GitHub
    auth_token: 183bb4d650be1da439cea601566a7131e98cc4d5
    description: 'Appveyor Triggered Build'
    draft: false
    prerelease: false
    on:
        APPVEYOR_DEPLOY: true
